#!/bin/sh


if [ "$1" == "install" ]; then
    cmd="yarn install"

elif [ "$1" == "preview" ]; then
    cmd="gulp preview"

elif [ "$1" == "bundle" ]; then
    cmd="gulp bundle"

else
    echo "Usage:"
    echo "$0 COMMAND"
    echo ""
    echo "Commands:"
    echo "  install — install dependencies"
    echo "  preview — live preview of the UI"
    echo "  bundle  - build the zip bundle"
    echo ""
    exit 1
fi

if [ "$(uname)" == "Darwin" ]; then
    # Running on macOS.
    docker run --rm -it -v $(pwd):/antora -p 5252:5252 asamalik/antora-ui-builder $cmd

elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    # Running on Linux.

    if [ -f /usr/bin/podman ]; then
	podman run --rm -it -v $(pwd):/antora:z -p 5252:5252 asamalik/antora-ui-builder $cmd

    else
        echo ""
        echo "Error: Container runtime haven't been found on your system. Fix it by:"
        echo "$ sudo dnf install podman"
        exit 1
    fi
fi
